### ISSUE TITLE
Using an additional chip 23lcv1024 and external buttons?

### ISSUE THREAD

**Issue by lyovav** [karawin/Ka-Radio#3]
Hello, what benefits provide the use of an additional chip 23lcv1024,
and whether there is support for external control buttons?
Thank you with best regards Vladimir.

**Comment by karawin** [comment]
The additional chip increases the buffering of the played station in order to avoid silent gaps if the internet stream is not regular.  Recommended if you experiment too many gaps.

External controls: see https://github.com/karawin/Ka-Radio/blob/master/Hardware/KiCAD/controles/controles.pdf
The led is optional and must now be connected to GPIO2 instead of GPIO16.
Thanks for your interest.
